name: flutterbeir
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  dio: ^1.0.9
  common_utils: ^1.1.1
  json_annotation: ^2.0.0
  audioplayers: ^0.15.1
  banner_view: ^1.1.2
  rxdart: ^0.23.0
  video_player:
  chewie: ^0.9.7
  dash_chat: ^1.1.10
  uuid: ^2.0.1
  image_picker:
  shared_preferences:
  crypto: ^2.0.6
  convert:
  date_format: ^1.0.8
  package_info: ^0.4.0+2
  device_info:
  webview_flutter:




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  assets:
    - assets/images/banner01.jpg
    - assets/images/banner_default.jpg
    - assets/images/banner_music_default.jpg
    - assets/images/br_qrcode.jpg
    - assets/images/btn_login_normal.png
    - assets/images/btn_login_on.png
    - assets/images/button_gray.png
    - assets/images/button_orange.png
    - assets/images/chatfrom_bg_normal.9.png
    - assets/images/chatto_bg_normal.9.png
    - assets/images/circle.png
    - assets/images/default_paint.png
    - assets/images/dialog_bg.png
    - assets/images/dialog_close.png
    - assets/images/dialog_comment_grey.png
    - assets/images/dialog_comment_orange.png
    - assets/images/dialog_exit_btn_gray.png
    - assets/images/dialog_exit_orange.png
    - assets/images/dialog_header.png
    - assets/images/home_icon1.png
    - assets/images/home_icon2.png
    - assets/images/home_icon3.png
    - assets/images/home_icon4.png
    - assets/images/home_icon5.png
    - assets/images/homepage_buttom_arrow.png
    - assets/images/homepage_right_arrow.png
    - assets/images/ic_delete_grey.png
    - assets/images/ic_launcher.png
    - assets/images/ic_login_cancle_normal.png
    - assets/images/ic_login_cancle_on.png
    - assets/images/ic_login_qq_normal.png
    - assets/images/ic_login_qq_on.png
    - assets/images/ic_login_sina_normal.png
    - assets/images/ic_login_sina_on.png
    - assets/images/ic_login_wechat_normal.png
    - assets/images/ic_login_wechat_on.png
    - assets/images/icon120.png
    - assets/images/icon_chat_add.png
    - assets/images/icon_chat_expression.png
    - assets/images/icon_chat_photo.png
    - assets/images/icon_chat_photograph.png
    - assets/images/icon_chat_voice.png
    - assets/images/icon_share.png
    - assets/images/icon_voice_left1.png
    - assets/images/icon_voice_left2.png
    - assets/images/icon_voice_left3.png
    - assets/images/icon_voice_right1.png
    - assets/images/icon_voice_right2.png
    - assets/images/icon_voice_right3.png
    - assets/images/me_aboutus.png
    - assets/images/me_feedback.png
    - assets/images/me_good.png
    - assets/images/me_header.png
    - assets/images/me_help.png
    - assets/images/me_phone.png
    - assets/images/me_share.png
    - assets/images/me_wechat.png
    - assets/images/me_yinsi.png
    - assets/images/music_home_age1.png
    - assets/images/music_home_age2.png
    - assets/images/music_home_age3.png
    - assets/images/music_home_age4.png
    - assets/images/music_home_age5.png
    - assets/images/music_home_icon1.png
    - assets/images/music_home_icon2.png
    - assets/images/music_home_icon3.png
    - assets/images/music_home_icon4.png
    - assets/images/music_home_icon5.png
    - assets/images/playing_collect_normal.png
    - assets/images/playing_collect_selected.png
    - assets/images/playing_share.png
    - assets/images/playing_status1.png
    - assets/images/playing_status2.png
    - assets/images/playing_status3.png
    - assets/images/playing_zan.png
    - assets/images/record_bottom.png
    - assets/images/record_top.png
    - assets/images/story_lock.png
    - assets/images/story_pause.png
    - assets/images/story_play.png
    - assets/images/tab1_normal.png
    - assets/images/tab1_selected.png
    - assets/images/tab2_normal.png
    - assets/images/tab2_selected.png
    - assets/images/tab3_normal.png
    - assets/images/tab3_selected.png
    - assets/images/tab4_normal.png
    - assets/images/tab4_selected.png
    - assets/images/tab5_normal.png
    - assets/images/tab5_selected.png
    - assets/privacy.html
